### ISSUE TITLE
exists Method for EMFRepoistory

### ISSUE THREAD

**Issue by juergen-albert** [geckoprojects-org/org.gecko.emf.persistence#3]
A convenience Method like `exists(EClass eClass, Object id)` would  be helpful.

**Comment by isalvadori** [comment]
@juergen-albert  Fixed in https://github.com/geckoprojects-org/org.gecko.emf.persistence/tree/issue3-exists-method-emf-repo. 
Could you please have a look?

**Comment by juergen-albert** [comment]
@isalvadori this should do for now. We may revisit this again, when @maho7791 is back, as I believe that he now also has a native method to ask the DB directly if something exists. With the current solution, we would always load the Object which might be large.

**Comment by maho7791** [comment]
In the new version, we will take the native methods from the drivers

**Comment by isalvadori** [comment]
OK, then I will close the issue for now.
